### ISSUE TITLE
Occasionally getting Error: Object Graph cannot be null

### ISSUE THREAD

**Issue by hareeshmu** [acdvorak/named-pipe-wrapper#33]
Seeing this error occasionally. Any fix can be applied?

Object Graph cannot be null.
Parameter name: graph
mscorlib
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at NamedPipeWrapper.IO.PipeStreamWriter`1.Serialize(T obj) in C:\BitBucket\named-pipe-wrapper\NamedPipeWrapper\IO\PipeStreamWriter.cs:line 42
   at NamedPipeWrapper.NamedPipeConnection`2.WritePipe() in C:\BitBucket\named-pipe-wrapper\NamedPipeWrapper\NamedPipeConnection.cs:line 167
   at NamedPipeWrapper.Threading.Worker.DoWorkImpl(Object oAction) in C:\BitBucket\named-pipe-wrapper\NamedPipeWrapper\Threading\Worker.cs:line 46

**Comment by fernandoEhp** [comment]
Same issue here

**Comment by metscore** [comment]
Unfortunately I also experience this problem.

**Comment by metscore** [comment]
A comment on this one:

I have a test program that I can run a few hundred times before the error appears. 

However, if I replaced the NuGet package, by downloading the source code (and upgraded the project to .net 4.8), and recompiled, I can run the same test program 15000 times without seeing the issue.
I'm not 100% sure why (I did not make any code changes) but the problem does not appear anymore.
